version: '3.8'

services:
  discord-music-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - MUSICBRAINZ_APP_NAME=${MUSICBRAINZ_APP_NAME}
      - MUSICBRAINZ_VERSION=${MUSICBRAINZ_VERSION}
      - MUSICBRAINZ_CONTACT=${MUSICBRAINZ_CONTACT}
    volumes:
      - ./logs:/app/logs
    labels:
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/discord.png"
      - "net.unraid.docker.webui=false"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"